@startuml

class Blockchain {
  -chain: Array
  +createGenesisBlock(): Block
  +addBlock(block: Block): void
  +validateBlock(block: Block): boolean
  +getLastBlock(): Block
  +getBlockchain(): Array
}

class Block {
  -index: int
  -timestamp: Date
  -nonce: string
  -hash: string
  -previousBlockHash: string
  +createBlock(index: int, nonce: string, hash: string, previousBlockHash: string): Block
}

class Miner {
  -blockchain: Blockchain
  -minerId: string
  +hashBlock(previousBlockHash: string, nonce: string): string
  +proofOfWork(previousBlockHash: string): int
  +mineBlock(): Block
  +isValidHash(blockHash: string): boolean
}

Blockchain "1" *-- "0..*" Block : has
Miner o-- Blockchain : association

@enduml






