@startuml b,

class Blockchain {
    - chain: array
    - pendingTransactions: array

    + Blockchain()
    + createNewBlock(nonce, previousBlockHash, hash): object
    + getLastBlock(): object
    + createNewTransaction(amount, sender, recipient): integer
    + hashBlock(previousBlockHash, currentBlockData, nonce): string
    + proofOfWork(previousBlockHash, currentBlockData): integer
}

@enduml

